#!/usr/bin/env python
"""
Cookie Helper Utility for Facebook Scraper.

This utility helps you:
1. Extract cookies from a logged-in browser session
2. Save cookies to fb_credentials.py for automated login
3. Validate if saved cookies are still valid
"""

import json
import logging
import time
from pathlib import Path
from typing import Dict, Optional

from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

try:
    from webdriver_manager.firefox import GeckoDriverManager
    WEBDRIVER_MANAGER_AVAILABLE = True
except ImportError:
    WEBDRIVER_MANAGER_AVAILABLE = False

logger = logging.getLogger(__name__)

# Essential Facebook cookies for session persistence
ESSENTIAL_COOKIES = ['c_user', 'xs', 'datr', 'sb', 'fr']


def create_browser(headless: bool = False) -> webdriver.Firefox:
    """Create a Firefox browser instance"""
    options = FirefoxOptions()
    
    if headless:
        options.add_argument("--headless")
    
    if WEBDRIVER_MANAGER_AVAILABLE:
        service = FirefoxService(GeckoDriverManager().install())
    else:
        service = FirefoxService("geckodriver")
    
    driver = webdriver.Firefox(service=service, options=options)
    driver.set_window_size(1366, 768)
    return driver


def extract_cookies_from_browser(driver: webdriver.Firefox) -> Dict[str, str]:
    """
    Extract essential Facebook cookies from a browser session.
    
    Returns:
        Dictionary of cookie name -> value
    """
    all_cookies = driver.get_cookies()
    essential = {}
    
    for cookie in all_cookies:
        if cookie['name'] in ESSENTIAL_COOKIES:
            essential[cookie['name']] = cookie['value']
    
    # Also capture any other useful cookies
    for cookie in all_cookies:
        if cookie['domain'] == '.facebook.com' and cookie['name'] not in essential:
            if cookie['name'] in ['wd', 'dpr', 'locale']:
                essential[cookie['name']] = cookie['value']
    
    return essential


def save_cookies_to_file(cookies: Dict[str, str], filepath: Optional[Path] = None):
    """
    Save cookies to fb_credentials.py file.
    
    Args:
        cookies: Dictionary of cookie name -> value
        filepath: Path to save the file (default: ../fb_credentials.py)
    """
    if filepath is None:
        filepath = Path(__file__).parent.parent / 'fb_credentials.py'
    
    # Read existing file to preserve credentials
    existing_email = ""
    existing_password = ""
    
    if filepath.exists():
        try:
            with open(filepath, 'r') as f:
                content = f.read()
                for line in content.split('\n'):
                    if line.startswith('FB_EMAIL'):
                        existing_email = line.split('=', 1)[1].strip().strip('"\'')
                    elif line.startswith('FB_PASSWORD'):
                        existing_password = line.split('=', 1)[1].strip().strip('"\'')
        except Exception as e:
            logger.warning(f"Could not read existing credentials: {e}")
    
    # Generate new file content
    cookie_str = json.dumps(cookies, indent=4)
    
    new_content = f'''# Facebook credentials - DO NOT SHARE!
# Generated by cookie_helper.py on {time.strftime("%Y-%m-%d %H:%M:%S")}

# Email and password for manual/automated login if needed
FB_EMAIL = "{existing_email}"
FB_PASSWORD = "{existing_password}"

# Cookie-based authentication (extracted from browser session)
# These cookies enable automatic login without entering credentials
cookies = {cookie_str}
'''
    
    with open(filepath, 'w') as f:
        f.write(new_content)
    
    print(f"Cookies saved to {filepath}")
    return True


def validate_cookies(cookies: Dict[str, str]) -> bool:
    """
    Check if the saved cookies contain all essential values.
    
    Returns:
        True if all essential cookies are present
    """
    missing = []
    for name in ESSENTIAL_COOKIES:
        if name not in cookies:
            missing.append(name)
    
    if missing:
        logger.warning(f"Missing essential cookies: {missing}")
        return False
    
    return True


def interactive_cookie_extraction():
    """
    Interactive mode to extract cookies from a browser session.
    Opens Firefox, waits for user to log in, then extracts cookies.
    """
    print("\n" + "="*60)
    print("FACEBOOK COOKIE EXTRACTION UTILITY")
    print("="*60)
    print("\nThis utility will:")
    print("1. Open a Firefox browser window")
    print("2. Navigate to Facebook")
    print("3. Wait for you to log in manually")
    print("4. Extract and save your session cookies")
    print("\nThese cookies will enable automatic login in the scraper.")
    print("="*60 + "\n")
    
    input("Press Enter to start...")
    
    driver = None
    try:
        print("Starting browser...")
        driver = create_browser(headless=False)
        
        print("Navigating to Facebook...")
        driver.get("https://www.facebook.com")
        
        print("\n" + "="*60)
        print("INSTRUCTIONS:")
        print("1. Log in to Facebook in the browser window")
        print("2. Complete any security checks if prompted")
        print("3. Once you're logged in and see your feed, come back here")
        print("="*60)
        
        input("\nPress Enter when you are logged in...")
        
        # Wait a moment for any final page loads
        time.sleep(2)
        
        # Check if on Facebook and logged in
        current_url = driver.current_url.lower()
        if 'facebook.com' in current_url and 'login' not in current_url:
            print("\nExtracting cookies...")
            cookies = extract_cookies_from_browser(driver)
            
            if validate_cookies(cookies):
                print(f"\nExtracted {len(cookies)} cookies successfully!")
                save_cookies_to_file(cookies)
                print("\n✓ Cookies saved! You can now run the scraper with automatic login.")
            else:
                print("\n⚠ Some essential cookies may be missing.")
                print("The login might not work properly.")
                save = input("Save anyway? (y/n): ").strip().lower()
                if save == 'y':
                    save_cookies_to_file(cookies)
        else:
            print("\n✗ It looks like you're still on the login page.")
            print("Please try again and make sure you're fully logged in.")
            
    except Exception as e:
        print(f"\n✗ Error: {e}")
        logger.error(f"Cookie extraction failed: {e}")
        
    finally:
        if driver:
            print("\nClosing browser...")
            driver.quit()
            print("Done!")


def main():
    """Main entry point for cookie helper"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Facebook Cookie Helper")
    parser.add_argument('--extract', action='store_true', 
                       help='Start interactive cookie extraction')
    parser.add_argument('--validate', action='store_true',
                       help='Validate existing cookies in fb_credentials.py')
    
    args = parser.parse_args()
    
    if args.validate:
        try:
            # Import existing cookies
            import sys
            sys.path.insert(0, str(Path(__file__).parent.parent))
            from fb_credentials import cookies
            
            print("Validating existing cookies...")
            if validate_cookies(cookies):
                print("✓ All essential cookies are present!")
                print(f"  Cookies found: {list(cookies.keys())}")
            else:
                print("✗ Some essential cookies are missing.")
                print("  Run with --extract to get new cookies.")
        except ImportError:
            print("✗ No cookies found in fb_credentials.py")
            print("  Run with --extract to get cookies.")
            
    elif args.extract:
        interactive_cookie_extraction()
    else:
        # Default to extraction
        interactive_cookie_extraction()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
