import os
import glob
import re

directories = ['src/components', 'src/components/ui']
replacements = {
    # PredictiveAnalysis.tsx
    'Analysis failed. Check the Gemini API configuration and try again.': 'Шинжилгээ амжилтгүй боллоо. Gemini API тохиргоог шалгаад дахин оролдоно уу.',
    'Prediction controls': 'Таамаглалын удирдлага',
    'Generate an AI summary from recent live posts, with demo data as fallback.': 'Сүүлийн үеийн бодит постуудаас AI хураангуй үүсгэх (туршилтын өгөгдлийг нөөц болгон ашиглана).',
    'Generating report': 'Тайлан үүсгэж байна',
    'Generate AI report': 'AI тайлан үүсгэх',
    '>Input scope<': '>Оролтын цар хүрээ<',
    'The prompt combines platform, date, post count, engagement, reach estimate, and sentiment baseline.': 'Энэ хүсэлт нь платформ, огноо, постын тоо, хандалт, хүртээмжийн таамаглал болон хандлагын суурийг нэгтгэдэг.',
    '>Sentiment<': '>Хандлага<',
    '>Topics<': '>Сэдвүүд<',
    'Model signals': 'Загварын дохио',
    'How the report interprets the collected data.': 'Тайлан цуглуулсан өгөгдлийг хэрхэн тайлбарлах.',
    'Sentiment drift': 'Хандлагын өөрчлөлт',
    'Detects shifts in positive, neutral, and negative tone.': 'Эерэг, саармаг болон сөрөг өнгө аясын өөрчлөлтийг илрүүлдэг.',
    'Engagement window': 'Хандалтын цонх',
    'Highlights periods where activity clusters.': 'Идэвхжил хамгийн их бөөгнөрсөн үеийг онцолдог.',
    'Recommendation synthesis': 'Зөвлөмжийн нэгтгэл',
    'Turns raw trends into operational next steps.': 'Түүхий чиг хандлагыг дараагийн бодит алхмууд болгон хувиргадаг.',
    'AI generated report': 'AI үүсгэсэн тайлан',
    'Readable output for presentation, review, or admin decisions.': 'Танилцуулга, хяналт болон админы шийдвэрт зориулагдсан уншихад хялбар үр дүн.',
    '>Ready for synthesis<': '>Нэгтгэл хийхэд бэлэн<',
    'Generate a report to summarize trends, engagement risks, and content opportunities.': 'Чиг хандлага, хандалтын эрсдэл болон контентын боломжуудыг нэгтгэсэн тайлан үүсгэх.',
    'Live data when available': 'Боломжтой үед бодит өгөгдөл',
    'demo fallback otherwise': 'эсвэл туршилтын нөөц өгөгдөл',

    # GeminiDataAnalyzer.tsx
    'An unexpected error occurred during analysis.': 'Шинжилгээний явцад гэнэтийн алдаа гарлаа.',
    'Gemini Data Analysis': 'Gemini өгөгдлийн шинжилгээ',
    'Structured JSON insights generated by Gemini 2.0 Flash.': 'Gemini 2.0 Flash тэвчнээс үүсгэгдсэн бүтэцжсэн JSON дүн шинжилгээ.',
    'Analyzing...': 'Шинжилж байна...',
    'Run Gemini Analysis': 'Gemini шинжилгээг ажиллуулах',
    'Click the button above to generate structured insights.': 'Дээрх товчийг дарж бүтэцжсэн дүн шинжилгээг үүсгэнэ үү.',
    'Sentiment Summary': 'Хандлагын хураангуй',
    'Key Themes': 'Гол сэдвүүд',
    'Engagement Risks': 'Хандалтын эрсдэлүүд',
    'Content Opportunities': 'Контентын боломжууд',

    # Overview.tsx
    'AI Overview': 'AI Тойм',
    'Beginner-friendly introduction to the AI concepts powering this system.': 'Энэ системийг ажиллуулдаг AI ойлголтуудын анхан шатны танилцуулга.',
    '>Note:<': '>Тэмдэглэл:<',
    'This page introduces key artificial intelligence concepts used in this': 'Энэ хуудас нь системийг ажиллуулж буй хиймэл оюун ухааны гол ойлголтуудыг танилцуулна. ',
    'Social Media Analysis System. The system uses the': 'Систем нь',
    'to standardize integrating AI models': '-г ашиглан дэмжигдсэн үйлчилгээ үзүүлэгчдийн AI загваруудыг стандартчилж',
    'across supported providers, enabling us to focus on building great analysis features': 'шинжилгээний функцуудыг бүтээхэд анхаарах боломжийг олгодог.',
    'instead of wasting time on technical details.': 'техникийн нарийн ширийн зүйлсэд цаг үрэлгүйгээр.',
    '>Generative AI<': '>Үүсгэгч AI<',
    'Systems that generate new text, images, or code based on patterns learned from vast amounts of training data.': 'Их хэмжээний өгөгдлөөс суралцсан хэв маягт үндэслэн шинэ текст, зураг, эсвэл код үүсгэдэг системүүд.',
    '>Large Language Models (LLMs)<': '>Томоохон хэлний загварууд (LLMs)<',
    'A type of Generative AI specifically trained to understand and generate human language. Examples include Gemini, GPT-4, and Claude.': 'Хүний хэлийг ойлгож, үүсгэж чаддаг Үүсгэгч AI-н нэг төрөл. Жишээ нь: Gemini, GPT-4, Claude.',
    '>Embedding Models<': '>Эмбеддинг загварууд<',
    'AI models that convert text into mathematical vectors (lists of numbers). This allows systems to measure how semantically similar two pieces of text are.': 'Текстийг математик вектор (тоон жагсаалт) руу хөрвүүлдэг AI загварууд. Энэ нь системд текстүүдийн утгын ижил төстэй байдлыг хэмжих боломжийг олгодог.',
    '>Prompt Engineering<': '>Промпт Инженерчлэл<',
    'The practice of designing highly specific instructions to guide an LLM toward producing the desired output format and tone.': 'Хүссэн үр дүн, өнгө аясыг гаргахын тулд LLM-д нарийвчилсан зааварчилгаа боловсруулах үйл явц.'
}

for d in directories:
    for root, dirs, files in os.walk(d):
        for f in files:
            if f.endswith('.tsx'):
                filepath = os.path.join(root, f)
                with open(filepath, 'r', encoding='utf-8') as file:
                    content = file.read()
                
                for en, mn in replacements.items():
                    if en.startswith('>'):
                        content = content.replace(en, mn)
                    else:
                        content = content.replace(f"'{en}'", f"'{mn}'")
                        content = content.replace(f'"{en}"', f'"{mn}"')
                        content = content.replace(f'>{en}<', f'>{mn}<')
                        
                with open(filepath, 'w', encoding='utf-8') as file:
                    file.write(content)

print("Translation applied.")