services:
  - type: web
    name: diplom-data-api
    runtime: python
    pythonVersion: 3.11
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    buildCommand: pip install -r requirements.txt
    healthCheckPath: /health
    envVars:
      - key: FB_SCRAPER_API_TOKEN
        scope: run
        value: ${FB_SCRAPER_API_TOKEN}
      - key: FIREBASE_CREDENTIALS
        scope: run
        value: /etc/secrets/firebase_credentials.json
      - key: PORT
        scope: run
        value: 8000
    secretFiles:
      - name: firebase_credentials
        destPath: /etc/secrets/firebase_credentials.json
