/**
 * GeminiDataAnalyzer Component
 * 
 * Minimal frontend component that triggers the /api/analyze-gemini route with aggregated data.
 * Displays the structured JSON results (themes, risks, opportunities, sentiment) using Lucide icons.
 */

import { useState } from 'react';
import { Sparkles, Loader2, AlertTriangle, Lightbulb, Activity, FileText } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { mockSocialData } from '../lib/mockData';
import { getBackendPosts, normalizeBackendPosts } from '../lib/backend';
import { ScrollArea } from './ui/scroll-area';

type AnalysisResult = {
  sentiment_summary: string;
  key_themes: string[];
  engagement_risks: string[];
  content_opportunities: string[];
};

export function GeminiDataAnalyzer() {
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      // 1. Fetch & aggregate data to avoid sending full raw tables to AI
      let dataToAnalyze;
      try {
        const posts = await getBackendPosts(50);
        if (posts.length > 0) {
          const livePosts = normalizeBackendPosts(posts);
          dataToAnalyze = livePosts.reduce<any[]>((acc, post) => {
            acc.push({
              platform: post.platform,
              engagement: post.engagement,
              date: post.date
            });
            return acc;
          }, []);
        } else {
          dataToAnalyze = mockSocialData;
        }
      } catch (err) {
        console.warn('Backend fetch failed, falling back to mock data', err);
        dataToAnalyze = mockSocialData;
      }

      // 2. Call our new Gemini API route
      const response = await fetch('/api/analyze-gemini', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ data: dataToAnalyze })
      });

      const json = await response.json();

      if (!response.ok) {
        throw new Error(json.error || 'Failed to fetch analysis');
      }

      // 3. Update state with typed JSON response
      setResult(json as AnalysisResult);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An unexpected error occurred during analysis.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="mt-5 border-violet-100 bg-violet-50/30">
      <CardHeader className="border-b border-slate-200 pb-4">
        <div className="flex items-center justify-between gap-3">
          <div>
            <CardTitle className="text-violet-950 flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-violet-600" />
              Gemini Data Analysis
            </CardTitle>
            <CardDescription>Structured JSON insights generated by Gemini 2.0 Flash.</CardDescription>
          </div>
          <Button onClick={handleAnalyze} disabled={loading} variant="outline" className="border-violet-200 bg-white text-violet-700 hover:bg-violet-50">
            {loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Sparkles className="h-4 w-4 mr-2" />}
            {loading ? 'Analyzing...' : 'Run Gemini Analysis'}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="pt-5 min-h-[300px]">
        {error && (
          <div className="rounded-md bg-red-50 p-4 text-sm text-red-700 border border-red-200 flex items-start gap-3 mb-4">
            <AlertTriangle className="h-5 w-5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {!result && !error && !loading && (
          <div className="flex h-[250px] flex-col items-center justify-center text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-violet-100 text-violet-600 mb-3">
              <Sparkles className="h-6 w-6" />
            </div>
            <p className="text-sm font-medium text-slate-700">Click the button above to generate structured insights.</p>
          </div>
        )}

        {result && (
          <ScrollArea className="h-[400px] pr-4">
            <div className="space-y-6">
              <div>
                <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-900 mb-2">
                  <Activity className="h-4 w-4 text-blue-600" />
                  Sentiment Summary
                </h4>
                <p className="text-sm leading-6 text-slate-700 bg-white p-3 rounded-lg border border-slate-200">
                  {result.sentiment_summary}
                </p>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-900 mb-2">
                    <FileText className="h-4 w-4 text-emerald-600" />
                    Key Themes
                  </h4>
                  <ul className="space-y-2">
                    {result.key_themes?.map((theme, i) => (
                      <li key={i} className="text-sm text-slate-700 bg-white p-2 rounded-md border border-slate-200 flex items-center gap-2">
                        <span className="h-1.5 w-1.5 rounded-full bg-emerald-500"></span>
                        {theme}
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-900 mb-2">
                    <AlertTriangle className="h-4 w-4 text-amber-600" />
                    Engagement Risks
                  </h4>
                  <ul className="space-y-2">
                    {result.engagement_risks?.map((risk, i) => (
                      <li key={i} className="text-sm text-slate-700 bg-white p-2 rounded-md border border-slate-200 flex items-center gap-2">
                        <span className="h-1.5 w-1.5 rounded-full bg-amber-500"></span>
                        {risk}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div>
                <h4 className="flex items-center gap-2 text-sm font-semibold text-slate-900 mb-2">
                  <Lightbulb className="h-4 w-4 text-purple-600" />
                  Content Opportunities
                </h4>
                <ul className="grid gap-2 sm:grid-cols-2">
                  {result.content_opportunities?.map((opp, i) => (
                    <li key={i} className="text-sm text-slate-700 bg-white p-3 rounded-lg border border-slate-200 flex items-start gap-2 shadow-sm">
                      <Sparkles className="h-4 w-4 text-purple-500 shrink-0 mt-0.5" />
                      <span>{opp}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}
